[alias]
client-sdk-generator = "run -p client_sdk_generator --release --"
client-sdk-generator-dev = "run -p client_sdk_generator --"
create-schema = "run -p client_sdk_schema --"
format = "fmt --all --verbose"
lint = "clippy --workspace --all-targets -- --deny warnings"

[profile.release]
lto = true
