# Based on: https://github.com/biomejs/biome/blob/a27b8253b2f0d5e5618e9b26eebaaa5da55ed69a/.github/actions/free-disk-space/action.yaml
# Copyright (c) 2025 Biome Developers and Contributors (MIT License)

name: Free Disk Space
description: Free up disk space on the runner
runs:
  using: composite
  steps:
    - name: Free Disk Space (Ubuntu)
      if: runner.os == 'Linux'
      uses: xc2/free-disk-space@fbe203b3788f2bebe2c835a15925da303eaa5efe # v1.0.0
      with:
        # We need to reclaim some space, but uninstalling everyting takes
        # too long. So we'll just remove some of the larger packages.
        # https://github.com/jlumbroso/free-disk-space/pull/26
        android: true
        dotnet: true
        haskell: true
        large-packages: false
